### ISSUE TITLE
ERROR: SyntaxError: Unexpected end of JSON input while running `npx staticshape@latest`

### ISSUE THREAD

**Issue by ccthecode** [CloudCannon/staticshape#6]
While running `npx staticshape@latest`, I get the error

### FOLDER STRUCTURE

```
├───static-hugo
└───static-next
    ├───config.json
```

- `config.json` was created before running the command and it's empty
- My static site lives in `static-next`
- I'm trying to output a Hugo site into `static-hugo`

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at file:///C:/Users/[USERNAME]/AppData/Local/npm-cache/_npx/9734112f603cd9ab/node_modules/staticshape/lib/index.js:122:21
```

### BUILD LOG

```
npx staticshape@latest
(node:12020) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(Use `node --trace-warnings ...` to show where the warning was created)
┌  Welcome to the StaticShape
│
◇  What folder contains your static site?
│  ./static-next
│
◆  Input set to C:\Users\[USERNAME]\code\js\portfolio-port\static-next
│
◇  Where is your staticshape config file?
│  ./config.json
│
◆  Input set to C:\Users\[USERNAME]\code\js\portfolio-port\config.json
│
◇  What folder should we output your SSG site?
│  ./_output/
│
◆  Input set to C:\Users\[USERNAME]\code\js\portfolio-port\_output
│
◇  What SSG would you like to use?
│  Hugo
│
▲  Something went wrong
undefined:2


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at file:///C:/Users/[USERNAME]/AppData/Local/npm-cache/_npx/9734112f603cd9ab/node_modules/staticshape/lib/index.js:122:21
```

**Comment by georgephillips** [comment]
Hey there 👋, thanks for trying out StaticShape. I have released a new version on npm to show a better error if your JSON is malformed. Can you try it out and let me know how it goes? If that doesn't work, can you provide your config.json?

**Comment by ccthecode** [comment]
Hi @georgephillips, I truly appreciate your efforts.

So I added this to the `config.json` file and I now getting this ERROR:

```
▲  Something went wrong
file:///C:/Users/[USERNAME]/AppData/Local/npm-cache/_npx/9734112f603cd9ab/node_modules/staticshape/lib/collection.js:45
        let current = baseDoc.diff(documents[1]);
```
